### ISSUE TITLE
How to focus on a li tag within a submenu?

### ISSUE THREAD

**Issue by hadithmv** [christophery/pushy#140]
Hi again @christophery 

It says in the readme:

**data-focus**
Use the data-focus attribute to give focus to a link when the menu is opened. Ideally the first link of the menu should be focused.
This data attribute accepts a CSS selector.
```
<nav class="pushy pushy-left" data-focus="#home-link">
    <div class="pushy-content">
        <ul>
            <li id="home-page" class="pushy-link"><a href="#">Home</a></li>
            <li class="pushy-link"><a href="#">About Us</a></li>
            <li class="pushy-link"><a href="#">Contact</a></li>
        </ul>
    </div>
</nav>
```

Any way to focus on one of the list items within a submenu?

**Comment by christophery** [comment]
You can't focus on a `<li>` tag, you can only focus on elements like `<button>` or anchor links. Technically you can apply it to an anchor link in the submenu but you won't see the focus since the submenu is closed by default. I only really intended it to be used on top level/parent menu links.

The `data-focus` attribute is for [keyboard focus](https://developers.google.com/web/fundamentals/accessibility/focus) which is an accessibility feature.

**Comment by djdance** [comment]
in the example above (from readme) I don't understand, why data-focus is #home-link, but li id=home-page
and it doesn't work for me
something is wrong here?

**Comment by christophery** [comment]
@djdance The example in the read me had an error, it's been resolved now. You can also look at the `demo.html` file for a working example too.
