### ISSUE TITLE
Menu Length Issues

### ISSUE THREAD

**Issue by casimirlancaster** [christophery/pushy#4]
I love this menu, however, I am experiencing the following issues when the length of the menu is longer than the page:
1. I am unable to scroll down to view the rest of the menu on the desktop and mobile. It would be great if there are 2 separate vertical scrollbars, one for the menu and the other for the page content.
2. When I resize the length of the browser while the menu is open, the menu's background color disappears. 

![screenshot-1](https://f.cloud.github.com/assets/3137481/1142232/fd53a05e-1cc7-11e3-832b-b87339613dbe.png)

![screenshot-2](https://f.cloud.github.com/assets/3137481/1142233/00dc4fbe-1cc8-11e3-9697-bf582fbaa6e8.png)

**Comment by unbreakablesense** [comment]
I know that this is an old thread, but I just stumbled across your menu and love it.  I'm beta testing my site right now and one person told me that the menu will be cutoff and unscrollable about 20% of the time on their iPhone6. I haven't had the opportunity to check on it myself, as I don't have an iPhone 6. No one else has reported this issue to me. Is this a known bug?

**Comment by joesayegh** [comment]
I love this menu, but I'm having the same problem as @unbreakablesense.

1. Open the [demo page] (https://www.christopheryee.ca/pushy) on an iPhone 6
2. Rotate your phone so that's in landscape mode
3. Now click the Menu button to reveal the Pushy menu
4. Click Submenu 3 to reveal the submenu links
5. If you try and scroll down on the Pushy menu now, you won't be able to view the links at the bottom.

I realise this is an old threat but I'm desperate to get this fixed.
Has anyone managed to get this fixed yet?
If so can you please provide the solution?
