### ISSUE TITLE
Hover show Menu

### ISSUE THREAD

**Issue by fantasia9** [christophery/pushy#85]
Hi Christophery, how to hover menu icon to show menu. Thanks.

**Comment by CHEWX** [comment]
Yes @fantasia9 

Add the following code to your JavaScript.

`
jQuery('.menu-btn').mouseenter(function() {
  jQuery(this).trigger('click');
});
`

**Comment by christophery** [comment]
Not a fan of triggering menu's using Hover, it's not that great for UX, it's often frustrating for the user and hover doesn't exist/work on mobile.

@CHEWX solution seems to do the trick, you won't be able to close the menu with hover since the site overlay covers it when it's opened (you could position the menu btn over the site overlay).
